INSERT INTO Users (username, email, pwd) VALUES
('alice', 'alice@email.com', 'pass1'),
('bob', 'bob@email.com', 'pass2'),
('carol', 'carol@email.com', 'pass3'),
('dave', 'dave@email.com', 'pass4'),
('eve', 'eve@email.com', 'pass5'),
('frank', 'frank@email.com', 'pass6'),
('grace', 'grace@email.com', 'pass7'),
('heidi', 'heidi@email.com', 'pass8'),
('ivan', 'ivan@email.com', 'pass9'),
('judy', 'judy@email.com', 'pass10');

INSERT INTO MovieGenres (genre) VALUES
('Action'),
('Comedy'),
('Drama'),
('Sci-Fi');

INSERT INTO Movies (title, date, mgid, poster, synopsis) VALUES
('Action Movie 1', '2022-01-01', 1, '../../resources/images/movie.png', 'Explosive action-packed adventure.'),
('Action Movie 2', '2022-02-01', 1, '../../resources/images/movie.png', 'Hero saves the day.'),
('Action Movie 3', '2022-03-01', 1, '../../resources/images/movie.png', 'High-speed car chases.'),
('Action Movie 4', '2022-04-01', 1, '../../resources/images/movie.png', 'Battle for justice.'),
('Action Movie 5', '2022-05-01', 1, '../../resources/images/movie.png', 'Mission impossible.'),
('Comedy Movie 1', '2022-01-10', 2, '../../resources/images/movie.png', 'Laugh-out-loud fun.'),
('Comedy Movie 2', '2022-02-10', 2, '../../resources/images/movie.png', 'Hilarious misadventures.'),
('Comedy Movie 3', '2022-03-10', 2, '../../resources/images/movie.png', 'Slapstick comedy.'),
('Comedy Movie 4', '2022-04-10', 2, '../../resources/images/movie.png', 'Family-friendly jokes.'),
('Comedy Movie 5', '2022-05-10', 2, '../../resources/images/movie.png', 'Romantic comedy.'),
('Drama Movie 1', '2022-01-20', 3, '../../resources/images/movie.png', 'Heartfelt story.'),
('Drama Movie 2', '2022-02-20', 3, '../../resources/images/movie.png', 'Emotional journey.'),
('Drama Movie 3', '2022-03-20', 3, '../../resources/images/movie.png', 'Tearjerker.'),
('Drama Movie 4', '2022-04-20', 3, '../../resources/images/movie.png', 'Family drama.'),
('Drama Movie 5', '2022-05-20', 3, '../../resources/images/movie.png', 'Coming of age.'),
('Sci-Fi Movie 1', '2022-01-30', 4, '../../resources/images/movie.png', 'Space adventure.'),
('Sci-Fi Movie 2', '2022-02-28', 4, '../../resources/images/movie.png', 'Alien encounter.'),
('Sci-Fi Movie 3', '2022-03-30', 4, '../../resources/images/movie.png', 'Time travel.'),
('Sci-Fi Movie 4', '2022-04-30', 4, '../../resources/images/movie.png', 'Futuristic world.'),
('Sci-Fi Movie 5', '2022-05-30', 4, '../../resources/images/movie.png', 'Robots and AI.');

INSERT INTO Playlist (uid, pname, date) VALUES (1, 'Favorites', '2023-01-01');

INSERT INTO UserRating (mid, rating, review) VALUES
(1, 5, 'Amazing action!'),
(1, 4, 'Really enjoyed it.'),
(1, 3, 'Good, but could be better.'),
(2, 4, 'Fun and exciting.'),
(2, 5, 'Best action movie!'),
(2, 2, 'Not my style.'),
(3, 3, 'Average action.'),
(3, 4, 'Nice stunts.'),
(3, 5, 'Loved the chase scenes.'),
(4, 2, 'Too loud.'),
(4, 3, 'Okay action.'),
(4, 4, 'Solid movie.'),
(5, 5, 'Great finale!'),
(5, 4, 'Good ending.'),
(5, 3, 'Enjoyed it.'),
(6, 4, 'Very funny!'),
(6, 5, 'Laughed a lot.'),
(6, 3, 'Silly but fun.'),
(7, 2, 'Not funny.'),
(7, 3, 'Some good jokes.'),
(7, 4, 'Enjoyable.'),
(8, 5, 'Hilarious!'),
(8, 4, 'Great cast.'),
(8, 3, 'Nice comedy.'),
(9, 4, 'Family loved it.'),
(9, 5, 'Best comedy!'),
(9, 2, 'Too cheesy.'),
(10, 3, 'Cute story.'),
(10, 4, 'Romantic and funny.'),
(10, 5, 'Loved it!'),
(11, 5, 'Very touching.'),
(11, 4, 'Well acted.'),
(11, 3, 'Good drama.'),
(12, 2, 'Too slow.'),
(12, 3, 'Emotional.'),
(12, 4, 'Nice plot.'),
(13, 5, 'Cried a lot.'),
(13, 4, 'Beautiful story.'),
(13, 3, 'Well written.'),
(14, 2, 'Not my type.'),
(14, 3, 'Decent drama.'),
(14, 4, 'Good acting.'),
(15, 5, 'Great coming of age.'),
(15, 4, 'Relatable.'),
(15, 3, 'Nice message.'),
(16, 4, 'Loved the effects.'),
(16, 5, 'Amazing sci-fi!'),
(16, 3, 'Cool story.'),
(17, 2, 'Too weird.'),
(17, 3, 'Interesting.'),
(17, 4, 'Good sci-fi.'),
(18, 5, 'Mind-blowing!'),
(18, 4, 'Great concept.'),
(18, 3, 'Fun to watch.'),
(19, 4, 'Loved the robots.'),
(19, 5, 'Best AI movie!'),
(19, 2, 'Too futuristic.'),
(20, 3, 'Nice ending.'),
(20, 4, 'Cool world.'),
(20, 5, 'Great sci-fi!');

INSERT INTO MoviePlaylist (pid, mid) VALUES (1, 1); 